# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1955d922f8ffcf33226c6e60a109a71c2284605a5bb8373bf7c4e7f1d0ec484fdd1cc0586985c08a10f66e54935750b9c8d3cdbf2c657c699218e81a93d3377e

test:
  secret_key_base: 95c1d94a5832c0de3ee3f51e97ce2b660f7a3dd378d0b81c43f2243d74f54c9df67f6696e62f518522ae9e0c3573b88d5b3e0a1c017aecd89e508bcba8914690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
